apiVersion: v1
kind: Secret
metadata:
    name: gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:mO28i8B0yG0tM8y/5Cu6TlGe8oyVvK/gTH+yw6HPQtNfS5T9tp9OFmpbcLM=,iv:UtQwgbrDIU8R0sMm0RUC8JXcV/Anr+4GP245obKwum0=,tag:F5COb4vsE8UJdX84lzQO7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUEl6SEM0VnNad005NjBQ
            ODh1RHphZThTMWxVOXBLMFEwWnliQVE5eGlFCjdsK21WSHhzV2k0WnBSVzYvWVZH
            eVZna3AybUdzaDBZemZQVzVMMGdhRU0KLS0tIEhZdzJwdlZZVmcyL3B6S2V2S05X
            RC9oSVN4SEZ6STdjQUUrNzZ3ODdWTTgKCUzc4wmlgmn2krPV3PHQ+Q5t1SnD6I15
            6hrJQkFMU7DVALYmQnNG79I7a/vw3mQ+nFlPwPBakwgz8WBFk2KsfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:44:33Z"
    mac: ENC[AES256_GCM,data:usEOKHIjkm8APDIqVGDtGV692DJB5jszVw05T3YcTC9BY3ZOH61eZiqC9D4qtX6lIlKxxl8fQrj2vu82py1/Da5J8fAT8XinpOnUCPL+becH4J+0No2wVBjA6fv71zSqeYmiiJaQwMd1J+1Uc0VFoLoVoZ3YtKewN2ILQON5tCA=,iv:0tLpF9vfXeK5y2YcULT37qgu2asvo4Hu5T0dI6UC4ug=,tag:62oT7r6Ld0RkswgtKGHx5g==,type:str]
    version: 3.13.1
