apiVersion: v1
kind: Secret
metadata:
    name: gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:bgig+4G1/soC/ecJhW/YgCl7xzbWjC0wKUhTe9FZ0fYXUUvaS+PW6RUxmM8=,iv:4M4+cnzy0oreU3bZ7ARBSUGqwwBBCaa5iwgvY9iPOWM=,tag:93KUIhU+p+nLIQwUvpu1pQ==,type:str]
sops:
    age:
        - recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aG04dndhdDRPUUZUNFRD
            clNEdGszOEFIUGJxSWlQVG9scy9EN3NGODBBClltbXRDeEIwajlXeWN5MVZHMklx
            aGFEWXluV1RkUEczcFhZTitVYUtZc00KLS0tIHNXS2NGTUpUUnA4U2YyRWZYRG9m
            TWZTcmRHaGZScEFaa2gySm9jM0gzamcKyx9kN4iT7Egxp9FXwWL62t3SwdSvuzqk
            6N4rRcYm6FxbKtS2ySou49zi8o+1v92OGgE1QfLzoO87MNiAqpphrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T17:30:10Z"
    mac: ENC[AES256_GCM,data:+rjeFH37Ry2mHpPDwnFuDGE7qwSbmRRXJHl4L6+3Af5VDtimAzY0w8EAB4X4c+On4G/ws8yCOZX76fOBCE4aamCEi82U49d3Ap9EmyEaYx+sein3REnT5P14f8iLBYkElJ2kXPmj0VVrB4OFz+bKstsjSPKTgi567Msd9d6QLMM=,iv:3kYOsEjKWZN7Vrb/jd42d9ifjYCNrxtOyI2gSIcpgKo=,tag:IuxH+q6GvC8jfkm5q8bFWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
