apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./gluetun.sops.yaml
  - ./prowlarr-config.yaml
  - ./qbittorrent-auth.sops.yaml
  - ./sonarr-anime-auth.sops.yaml
  - ./sonarr-config.yaml
  - ./sonarr-secret.sops.yaml
  - ./sonarr-tv-auth.sops.yaml
