apiVersion: v1
kind: Secret
metadata:
    name: sonarr
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:1rPh68RVKwsqAN6u9CjjhNQd4r5dBHK/UISAG1gLwSk=,iv:uweMOZSkdZ4VEFN12fieVAU13Q8uh9XOszmI5Imsqyg=,tag:XcfHYSapXOZgMUMEFZSZDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWDhESFM3SE4veFMzdnky
            Z0dQQVpkMHlDUmMxU1BaQ01tRnR1R3AvUTNRCktvMXd1dkxKMXAzLzJGUnFPVk9o
            Q05ld1NLK1owMWw1a2hneTM3Y0Izb28KLS0tIFc2S25DcElOSFEyZWVrOWg5cStX
            cjZOZmNZdVRnMVBRTDNvY1E5c0t3TWcKI2ml0+g2GednI8jqod0V/2+57YJ1wHUy
            uHdt73udTUGSxL37XgCo6uWw2Hz2cZlaks4mcnZkbXaw1SrYJee3mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T11:58:52Z"
    mac: ENC[AES256_GCM,data:pVLpyKecVZg8K/DbGX1H98CAWtHqxvqnkhYfqsw17lyv5GOxIrENNA0F0o2SbvZC+nZsdEqoyygeR1TFaKbplhWxNPnti9gaRFKY17afAoSSM7TkiijM/ZJsCZLG4eSvE2b8ERX0i+/u6thKkla+vmkawFAFIC2tLK2TwvMltX8=,iv:lwzMbLy+nRsujzbmwhEfgsCA4c/lZRQaYy6+k4N2VKA=,tag:qyvjZnSUvV6sxIqOwT6bZA==,type:str]
    version: 3.13.1
