apiVersion: v1
kind: Secret
metadata:
    name: gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:U7GR9mU4icnt48d+DuS8vUxNJqZBULjNdGVnfrZNlOuXAbL3n+7a6ySaXA4=,iv:Ni4EheOx+ci5HWE5NxvlqK8pUnXbIIBLGNPH3ONSy40=,tag:JIEAMEJWhMKS124i7NMSBQ==,type:str]
sops:
    age:
        - recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM0N1aHZhQkg2YmJTVklx
            UXUvbUNudWcrL3FBbldGUG11SXdXVTc3YmprCnNEbnNSVXVDdnVEY1BNOTdiZ3pC
            MFRtZnh6YUsvZkZEREMrMnJaL0ZmVFEKLS0tIHhzT1pYalBsUmxnRE1vNzJJN0h4
            cndpdnZlQWFlS0FCaXhJNStZd2JCN1UKC9PcWY76dqoyq3B1CFtiIyJ2Qu8wjZmq
            aZD1TOtzPMSvnxu8YCpWwydrHKsAKht5oMfgUiifX1CK4cV8Snp5QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T17:30:15Z"
    mac: ENC[AES256_GCM,data:CWIGlKwHRhsBA4L68tWIcOd4kIf+6iO19qd0mK2eJirNrwe4Y3glj1J28QZYOHHxSHaO5m3NuvNJb8Dc13auUm8ZW2BFQB2yKqGqHQcR5cu8CZYtfP7fOopK8fzIzoML52zA53rkP/HYAjv33ABB0p0g6AF92/g0+4woh/d1lls=,iv:k0kQ6QhLFmgU3O/wqbzBoajSWQNsX3bxSpis94x1ZzU=,tag:zluDfZ5ikUSffQa74l63xQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
