apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./blocky.yaml
configMapGenerator:
  - name: blocky-grafana-dashboards
    files:
      - ./dashboards/blocky.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: blocky
        app.kubernetes.io/component: monitoring
