apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: wger
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/mirror/charts/wger
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wger
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: wger
  values: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wger
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: wger
    gethomepage.dev/description: Workout Tracker
    gethomepage.dev/group: Fitness
    gethomepage.dev/icon: wger.png
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: http
      namespace: kgateway
  hostnames:
    - wger.${CLUSTER_DOMAIN}
  rules:
    - backendRefs:
        - name: wger-http
          port: 8000
          weight: 1
