apiVersion: v1
kind: Secret
metadata:
    name: gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:EGDsYJ7IIwltVeMDSO9jRJ8jc1uehrhD8fIF7OqlN9h0xIIV0i5VUoOG6Js=,iv:Rqa3q189k9Z8kBTWJKAwBfF0ur8JbkSRXOxb1LuyQB4=,tag:rRKilU6eeY122Yn1qWcT9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVVdCM2kvaXF4U2tPcENy
            YTg0VVZFUktqWExGUHNwLzZIaEl3N1VwbVNZCjdhbk5reldNeUx3bkxnSElFYlcr
            SE9oa1JxTmJFVWplNXhjUkNGQmV3K0UKLS0tIENCVmNtUmNYQ0lmS2hpOTFUZmho
            eXYwd0NSbmRFMkh1czUyelowaVkvSHcK3+WtQ28WYfdAKe+FdFpTasf4i348mMvO
            BG42d31UlObwlHtP0HES7ptIQmGHOBGpzOLKg0DuNEPR9YoY7QmvMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:44:38Z"
    mac: ENC[AES256_GCM,data:JHaIN2LVUhY0V/P9z43kvqnIaG4FaEiF5KEh66F3GDz9CAVhnXbNFScmn1dn8y8ae6YqmS3SA1Etlh40X5Xb3B/qA7eeRFWtdeAQ/pjfFsYr9iJVpY/edkBJCO7YodXOgB6vcz1Qz2z6aDa5WjJd1TmLfY9NZPKsn+yHZuhvkC4=,iv:HQk3y0ugvcyO7/UZiAKa5yY3Pu+z55vZxk+ppWiRqf8=,tag:jTumfEyYsycg761zPkSxpA==,type:str]
    version: 3.13.1
