apiVersion: v1
kind: Secret
metadata:
  name: sonarr-auth
type: Opaque
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:FiinyJUX/8YCgLziGmvXhYsZapaXjbrjp6Y0q/9D/g0=,iv:bodSPFIkqcnXD/JKznHLzs1U72qquVXdmOW2XAzz+q4=,tag:qtcKN3HBUp4PGiq1w0F9FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscUdWYStuSFRPV0toVWI0
        UCtJRWVCU01mRFhpd0tmbGVDajIxRWRlZWhJCjdKSi83a3ZNNGU5Vk5PakVoS1Rk
        cG1qOHlOb1RFdFYzL3I4YVVZYlhFKzAKLS0tIGJxSDNIY015Z3lVRjFPL3ZXeElC
        ZDFHekYxN0ozTFlwdUVKZFhyYXpvUEkK9g5LKuHYyMzCo5cWsEv5m0TYgxb7FG6G
        ZcqkMITWx3Q6PiaHV5VN+JUup3Pr2fPeotiI+1ub75infPTFuqUuOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T11:58:59Z"
  mac: ENC[AES256_GCM,data:/VoUFE3nO0PIJS0xdKaqYERlTdLbbce40uqO8XL8nO30+3DsJkynSMb5CU88AYuGMvLfR3WHoMTVTymJLcDnbACx3foEjR9X9l7xBS8smEjn4GQEqZ7mhnE/rnitDxOubKFN11G9Y5G+IP5Jk3DYcg5AsZXIjGqzOpS7U1cej+M=,iv:zm7nCePmev7yZpyWv7bcklZ3gT+s7IYxS9z9K/SxS5s=,tag:aE8pWN0AdtBoTHBl3GG9Dg==,type:str]
  version: 3.13.1
