apiVersion: v1
kind: Secret
metadata:
    name: gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:vdSvcG2uDedYWB57LIaAB/XSFideJacQbik2tHWOT8QGX64SQOVxiyJQrNM=,iv:Xpga3QcWeyu9FDqLMIbU1mxsYsVZUwuCYWG6EjCMu78=,tag:sXqbwRD/zfutffs/gtaVvw==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:25Q=,iv:aAfFDkTXhK0+AC0niCORvdXaJZAYr9NuHa9mFMw7ARw=,tag:09iKzv4M4rGnbPUq0lg67A==,type:str]
    PORT_FORWARD_ONLY: ENC[AES256_GCM,data:0Pk=,iv:JhkoQlYCCqgqJY/EIjxNrpUNUj0Wl6p9JrwDwHMgDQ8=,tag:Dzh128MvxPS0kdo8ka59gQ==,type:str]
sops:
    age:
        - recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUzlseVltRDNnbFhpeTRv
            SzE1NTN1Sk5WSGFmdjNDU2ZuY1l5a2VGOVFzCkNQUVNxZksyTEFDQUtsdlRCVnVE
            cVdIeHMydFJ3NituYjVZU3l6S3BoWmcKLS0tIGNoR1E2TzNHWmJneUJtWVNVY0JT
            NGRwdWhnZmZ3Z1Y1ZUN1NHE2YnVLNlEKv0CJzYaOzH31yVeRLFWy5kVew8JaIGUN
            StV0iX8eFvVmFy6/c+lAO1rNwHbQ3om6LoZ4/A7N6dVN7DhF3ksEIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T22:38:43Z"
    mac: ENC[AES256_GCM,data:+ogkvJ0o1ck1sd4dttFreE35zUiPV32PvPiyzw/bZXpIgz1qX9cpTRoWbL1LbYpzYf6msHVJ34hdtimEeA7Ir1Fg16CIpsKU3B0rcU8nf2CZVSrWUGudU9KnNOxvqxYit2N9EOBVeP4PPfPf+A84cfJYCXIuBGcbzG4Bql3AQ6g=,iv:yBIv6xX72BVspsHE/PjXsdbgKFDlRv2tl4lVcXASU2s=,tag:aY6sdFWofmgLQi6nrcmzhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
