apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
charts:
  - name: jellyfin
    source: https://jellyfin.github.io/jellyfin-helm
    destination: oci://ghcr.io/ssouthcity/mirror/charts
    limit: 3
