apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: configarr
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/charts/configarr
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/ssouthcity/charts/\.github/workflows/publish-chart\.yaml@refs/heads/main$
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: configarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: configarr
  values:
    env:
      - name: SONARR_ANIME_API_KEY
        valueFrom:
          secretKeyRef:
            name: sonarr-anime-auth
            key: SONARR__AUTH__APIKEY
      - name: SONARR_TV_API_KEY
        valueFrom:
          secretKeyRef:
            name: sonarr-tv-auth
            key: SONARR__AUTH__APIKEY
      - name: QBITTORRENT_USERNAME
        valueFrom:
          secretKeyRef:
            name: qbittorrent-auth
            key: username
      - name: QBITTORRENT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: qbittorrent-auth
            key: password
    config:
      config.yml: |
        trashGuideUrl: https://github.com/TRaSH-Guides/Guides
        recyclarrConfigUrl: https://github.com/recyclarr/config-templates

        sonarr:
          sonarr-anime:
            base_url: http://sonarr-anime:8989
            api_key: !env SONARR_ANIME_API_KEY

            quality_definitions:
              type: anime

            include:
              - template: sonarr-quality-definition-anime
              - template: sonarr-v4-quality-profile-anime
              - template: sonarr-v4-custom-formats-anime

            root_folders:
              - /data/media/anime

            media_naming_api:
              renameEpisodes: true
              standardEpisodeFormat: "{Series CleanTitleWithoutYear} {(Series Year)} - S{season:00}E{episode:00} - {Episode CleanTitle:90} {[Custom Formats]}{[Quality Full]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo VideoCodec]}{-Release Group}"
              dailyEpisodeFormat: "{Series CleanTitleWithoutYear} {(Series Year)} - {Air-Date} - {Episode CleanTitle:90} {[Custom Formats]}{[Quality Full]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo VideoCodec]}{-Release Group}"
              animeEpisodeFormat: "{Series CleanTitleWithoutYear} {(Series Year)} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle:90} {[Custom Formats]}{[Quality Full]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoDynamicRangeType]}[{Mediainfo VideoCodec }{MediaInfo VideoBitDepth}bit]{-Release Group}"
              seriesFolderFormat: "{Series CleanTitleWithoutYear} {(Series Year)} [tvdbid-{TvdbId}]"
              seasonFolderFormat: "Season {season:00}"
              specialsFolderFormat: "Specials"
              multiEpisodeStyle: 5

            download_clients:
              data:
                - name: qBittorrent
                  type: qbittorrent
                  enable: true
                  priority: 1
                  remove_completed_downloads: true
                  remove_failed_downloads: true
                  tags: []
                  fields:
                    host: qbittorrent
                    port: 8080
                    use_ssl: false
                    url_base: /
                    username: !env QBITTORRENT_USERNAME
                    password: !env QBITTORRENT_PASSWORD
                    tv_category: anime
              delete_unmanaged:
                enabled: true

          sonarr-tv:
            base_url: http://sonarr-tv:8989
            api_key: !env SONARR_TV_API_KEY

            quality_definition:
              type: series

            include:
              - template: sonarr-quality-definition-series
              - template: sonarr-v4-quality-profile-web-1080p
              - template: sonarr-v4-custom-formats-web-1080p

            root_folders:
              - /data/media/tv

            media_naming_api:
              renameEpisodes: true
              standardEpisodeFormat: "{Series CleanTitleWithoutYear} {(Series Year)} - S{season:00}E{episode:00} - {Episode CleanTitle:90} {[Custom Formats]}{[Quality Full]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo VideoCodec]}{-Release Group}"
              dailyEpisodeFormat: "{Series CleanTitleWithoutYear} {(Series Year)} - {Air-Date} - {Episode CleanTitle:90} {[Custom Formats]}{[Quality Full]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo VideoCodec]}{-Release Group}"
              animeEpisodeFormat: "{Series CleanTitleWithoutYear} {(Series Year)} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle:90} {[Custom Formats]}{[Quality Full]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoDynamicRangeType]}[{Mediainfo VideoCodec }{MediaInfo VideoBitDepth}bit]{-Release Group}"
              seriesFolderFormat: "{Series CleanTitleWithoutYear} {(Series Year)} [tvdbid-{TvdbId}]"
              seasonFolderFormat: "Season {season:00}"
              specialsFolderFormat: "Specials"
              multiEpisodeStyle: 5

            download_clients:
              data:
                - name: qBittorrent
                  type: qbittorrent
                  enable: true
                  priority: 1
                  remove_completed_downloads: true
                  remove_failed_downloads: true
                  tags: []
                  fields:
                    host: qbittorrent
                    port: 8080
                    use_ssl: false
                    url_base: /
                    username: !env QBITTORRENT_USERNAME
                    password: !env QBITTORRENT_PASSWORD
                    tv_category: tv
              delete_unmanaged:
                enabled: true

        radarr: {}
