apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configarr.yaml
  - ./jellyfin.yaml
  - ./komga.yaml
  - ./prowlarr.yaml
  - ./pvc.yaml
  - ./qbittorrent.yaml
  - ./seerr.yaml
  - ./sonarr-anime.yaml
  - ./sonarr-tv.yaml
  - ./sonarr.yaml
