apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: qbittorrent
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/charts/qbittorrent
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/ssouthcity/charts/\.github/workflows/publish-chart\.yaml@refs/heads/main$
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  values:
    gluetun:
      enabled: true
      env:
        - name: VPN_SERVICE_PROVIDER
          value: "protonvpn"
        - name: VPN_TYPE
          value: "wireguard"
        - name: VPN_PORT_FORWARDING
          value: "on"
        - name: PORT_FORWARD_ONLY
          value: "on"
      envFrom:
        - secretRef:
            name: gluetun
    httpRoute:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: qBittorrent
        gethomepage.dev/description: Torrenting Client
        gethomepage.dev/group: Media
        gethomepage.dev/icon: qbittorrent.png
        gethomepage.dev/pod-selector: "app.kubernetes.io/instance=qbittorrent"
      parentRefs:
        - name: http
          namespace: kgateway
      hostnames:
        - qbittorrent.southcity.dev
    volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
    volumeMounts:
      - name: media
        mountPath: /downloads
        subPath: torrents
