apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sonarr-tv
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/charts/sonarr
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/ssouthcity/charts/\.github/workflows/publish-chart\.yaml@refs/heads/main$
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr-tv
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sonarr-tv
  values:
    envFrom:
      - configMapRef:
          name: sonarr-tv
      - secretRef:
          name: sonarr-tv-auth
    cnpg:
      enabled: true
    httpRoute:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Sonarr TV
        gethomepage.dev/description: PVR for Usenet and BitTorrent
        gethomepage.dev/group: Media
        gethomepage.dev/icon: sonarr.png
        gethomepage.dev/pod-selector: "app.kubernetes.io/instance=sonarr-tv"
      parentRefs:
        - name: http
          namespace: kgateway
      hostnames:
        - sonarr-tv.${CLUSTER_DOMAIN}
    volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
    volumeMounts:
      - name: media
        mountPath: /data/torrents/tv
        subPath: torrents/tv
      - name: media
        mountPath: /data/media/tv
        subPath: media/tv
